### ISSUE TITLE
docker start fails after a crash

### ISSUE THREAD

**Issue by Vlad777** [memsql/memsql-mesos#10]
After finding a docker container down, trying to start it always results in this error. At this point, I have to export the image to a tar, modify the startup script to remove the code that does this check and manually start the memsqld process.

*** Running /etc/my_init.d/00_regen_ssh_host_keys.sh...
*** Running /etc/my_init.d/executor...
2016-10-10 17:03:01,276 [INFO] kazoo.client: Connecting to zookeeper:2181
2016-10-10 17:03:01,284 [INFO] kazoo.client: Zookeeper connection established, state: CONNECTED
2016-10-10 17:03:01,309 [INFO] __main__: Starting MemSQL Executor
2016-10-10 17:03:01,325 [INFO] memsql_framework.executor.main: Downloading MemSQL Ops
2016-10-10 17:03:02,020 [INFO] memsql_framework.executor.main: Unpacking MemSQL Ops
2016-10-10 17:03:02,494 [INFO] memsql_framework.executor.main: Installing and starting MemSQL Ops
2016-10-10 17:03:03,071 [ERROR] __main__: Fail
Traceback (most recent call last):
  File "/memsql_framework/bin/executor", line 33, in <module>
    driver.start()
  File "/memsql_framework/memsql_framework/executor/main.py", line 56, in start
    run([ "/tmp/memsql_ops/install.sh", "--host", self.agent_host, "--port", self.agent_port, "--no-cluster" ])
  File "/memsql_framework/memsql_framework/executor/main.py", line 26, in run
    raise Exception("Command failed\n%s\n%s" % (stdout, stderr))
Exception: Command failed
Installing MemSQL Ops in /var/lib/memsql-ops
/var/lib/memsql-ops already exists and is nonempty

Starting Executor
*** /etc/my_init.d/executor failed with status 1

*** Killing all processes...

**Comment by choochootrain** [comment]
its unclear to me from the docs how mesos requests docker volumes - its possible that it is retrieving an old volume which was used by a previous task and so the directory already exists. 

can you verify if that is the case?
